language: cpp
sudo: required
dist: bionic
branches:
  only:
    - master
matrix:
  include:
  - os: linux
compiler: gcc
install:
  - sudo apt-get update -y
  - sudo apt install -y g++ qt5-default qtbase5-dev libqt5svg5-dev qtmultimedia5-dev qtwebengine5-dev libhunspell-dev pkg-config libqt5concurrent5 qttools5-dev-tools
script:
  - qmake && make
