version: 2.1.2-{build}
platform: x64
configuration: Release
image: Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.15.2\msvc2019_64
  - set PATH=%PATH%;%QTDIR%\bin
before_build:
  - call "%QTDIR%/bin/qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd %APPVEYOR_BUILD_FOLDER%
build_script:
  - qmake ghostwriter.pro
  - nmake release
  - mkdir deploy
  - cp build\release\ghostwriter.exe deploy
  - cd deploy
  - mkdir translations
  - cp '..\build\release\translations\**' translations
  - windeployqt ghostwriter.exe
branches:
  only: 
  - master
artifacts:
  - path: 'deploy\**'
    name: deploy files

  - path: 'build\**'
    name: object files
    type: zip
skip_non_tags: false
shallow_clone: true
