version: 2.1.2-{build}
platform: x64
configuration: Release
image: Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.15.2\msvc2019_64
  - set PATH=%PATH%;%QTDIR%\bin
before_build: 
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - qmake ghostwriter.pro
  - nmake release
after_build:
  - call "%QTDIR%/bin/qtenv2.bat"
  - mkdir ghostwriter-portable-2.1.2
  - cd ghostwriter-portable-2.1.2
  - cp ..\build\release\ghostwriter.exe .
  - windeployqt .\ghostwriter.exe
  - mkdir translations
  - cp ..\build\release\translations\*.qm translations
branches:
  only: 
  - master
artifacts:
  - path: C:\projects\ghostwriter\build\release\
   type: zip
skip_non_tags: false
shallow_clone: true
