name: fedora-copr-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install copr-cli
      run: | 
        sudo pip install copr-cli configparser
        copr-cli --version
    - name: Wait for Copr build
      run: sleep 3600
    - name: Fetch build status
      run: |
        export BUILD_STATUS=$(copr-cli list-builds wereturtle/staging | head -1 | awk -F ' '  '{ print $(NF)}')
        echo "Copr build status = $BUILD_STATUS"
    - name: Verify build status
      run: if [[ "$BUILD_STATUS" == "failed" ]]; then exit 1; fi
