# This is a basic workflow to help you get started with Actions

name: CI

uses: jurplel/install-qt-action@v2.11.1
with:
    # Host platform
    host: Ubuntu
    # Target platform for build
    target: desktop
    # Architecture for Windows/Android
    arch: x86-64
    # Whether or not to install Qt dependencies on Linux
    install-deps: # optional, default is true
    # Additional Qt modules to install
    modules: QtWebEngine
    # Whether or not to actually download Qt
    cached: true
    # Whether or not to automatically run setup-python to find a valid python version.
    setup-python: false

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Qt
        # You may pin to the exact commit or the version.
        # uses: jurplel/install-qt-action@a962fb91949c8e846a3e4a944d50e7ef5cc3a28a
        uses: jurplel/install-qt-action@v2.11.1
        with:
          # Additional Qt modules to install
          modules: QtWebEngine
          cached: true
          # Whether or not to automatically run setup-python to find a valid python version.
          setup-python: false
          
      # Runs a single command using the runners shell
      - name: Compile
        run: |
          qmake
          make
          make install
